# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches-ignore:
      - 'master' # no need to run after merging to master
      - 'main' # no need to run after merging to main; main is the "new" master
    pull_request:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Build module (with dependencies)
        run: mvn -B package --file pom.xml -DskipTests -Dsource.skip

      - name: Test module
        run: mvn verify --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end -Dsource.skip
        
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
  
